### ISSUE TITLE
场地预约问题

### ISSUE THREAD

**Issue by Zeh0814** [Xm798/NUAA-Court-Reservation#2]
同学，你好！“获取用户基本信息之后...”函数get_name（）中287行 r = response.json()报错，原因是response返回<Response [412]>，请问有什么解决办法没？

**Comment by Xm798** [comment]
412 一般是遇到 WAF 了吧

**Comment by zjl321725573** [comment]
兄弟，问一下，这个代码现在还可以使用吗？

**Comment by Xm798** [comment]
@zjl321725573 现在我已不在学校了，应该不能直接使用了，可能需要修改适配

**Comment by zjl321725573** [comment]
> @zjl321725573 现在我已不在学校了，应该不能直接使用了，可能需要修改适配

哦哦好的，谢谢！我已经研究一天了，对于不懂计算机语言的我真是太难了，哈哈哈
